//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_positions_dividends")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub account_number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub account_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub symbol: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub quantity: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub last_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub last_price_change: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub current_value: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub percent_of_account: Option<Decimal>,
    pub ex_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub amount_per_share: Option<Decimal>,
    pub pay_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub r#yield: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub est_annual_income: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    pub as_of_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hash: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
