//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "iq_report")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub stock: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub div_growth: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value_rating: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub dividend: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub r#yield: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub points_down: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub percent_down: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub undervalue_lo_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub undervalue_hi_yield: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub points_up: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub percent_up: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub overvalue_hi_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub overvalue_lo_yield: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sp_rating: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub lo_52_wk: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub hi_52_wk: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub book_value: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub earnings_12_mo: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub price_to_earnings: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub pay_out: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub div_in_dgr: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub long_term_debt: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 0)))", nullable)]
    pub bluechip_criteria: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub symbol: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sector: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub industry: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sub_sector: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub div_growth_3_year: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub div_growth_5_year: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub div_growth_10_year: Option<Decimal>,
    pub report_date: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
