create or replace view Account_Positions as
select overview_id,
       dividend_id,
       Account_Number,
       Account_Name,
       Symbol,
       Description,
       Quantity,
       Last_Price,
       Last_Price_Change,
       Current_Value,
       Percent_Of_Account,
       Today_Gain_Loss_Dollar,
       Today_Gain_Loss_Percent,
       Total_Gain_Loss_Dollar,
       Total_Gain_Loss_Percent,
       Cost_Basis_Total,
       Average_Cost_Basis,
       Ex_Date,
       Amount_Per_Share,
       Pay_Date,
       Yield,
       Est_Annual_Income,
       Type
from (select overview.id as overview_id,
             dividends.id as dividend_id,
             overview.Account_Number,
             overview.Account_Name,
             overview.Symbol,
             overview.Description,
             overview.Quantity,
             overview.Last_Price,
             overview.Last_Price_Change,
             overview.Current_Value,
             overview.Percent_Of_Account,
             Today_Gain_Loss_Dollar,
             Today_Gain_Loss_Percent,
             Total_Gain_Loss_Dollar,
             Total_Gain_Loss_Percent,
             Cost_Basis_Total,
             Average_Cost_Basis,
             Ex_Date,
             Amount_Per_Share,
             Pay_Date,
             Yield,
             Est_Annual_Income,
             overview.Type
      from Account_Positions_Overview overview
              full outer join Account_Positions_Dividends dividends
                         on overview.Symbol = dividends.Symbol and overview.Quantity = dividends.Quantity) data;