create table IQ_Report
(
    id                  INT GENERATED ALWAYS AS IDENTITY,
    Stock               TEXT,
    Div_Growth          TEXT,
    Value_Rating        TEXT,
    Price               DECIMAL(10, 2),
    Dividend            DECIMAL(10, 2),
    Yield               DECIMAL(10, 2),
    Points_Down         DECIMAL(10, 0),
    Percent_Down        DECIMAL(10, 0),
    Undervalue_Lo_Price DECIMAL(10, 0),
    Undervalue_Hi_Yield DECIMAL(10, 2),
    Points_Up           DECIMAL(10, 0),
    Percent_Up          DECIMAL(10, 0),
    Overvalue_Hi_Price  DECIMAL(10, 0),
    Overvalue_Lo_Yield  DECIMAL(10, 2),
    SP_Rating           TEXT,
    Lo_52_Wk            DECIMAL(10, 0),
    Hi_52_Wk            DECIMAL(10, 0),
    Book_Value          DECIMAL(10, 0),
    Earnings_12_Mo      DECIMAL(10, 2),
    Price_to_Earnings   DECIMAL(10, 0),
    Pay_Out             DECIMAL(10, 0),
    Div_In_Dgr          TEXT,
    Long_Term_Debt      DECIMAL(10, 0),
    Bluechip_Criteria   DECIMAL(10, 0),
    Symbol              TEXT,
    Sector              TEXT,
    Industry            TEXT,
    Sub_Sector          TEXT,
    Div_Growth_3_Year   DECIMAL(10, 2),
    Div_Growth_5_Year   DECIMAL(10, 2),
    Div_Growth_10_Year  DECIMAL(10, 2),
    Report_Date         DATE
);

