create table IQ_Report
(
    id                  INT GENERATED ALWAYS AS IDENTITY,
    stock               TEXT,
    div_growth          TEXT,
    value_rating        TEXT,
    price               DECIMAL(10, 2),
    dividend            DECIMAL(10, 2),
    yield               DECIMAL(10, 2),
    points_down         DECIMAL(10, 0),
    percent_down        DECIMAL(10, 0),
    undervalue_lo_price DECIMAL(10, 0),
    undervalue_hi_yield DECIMAL(10, 2),
    points_up           DECIMAL(10, 0),
    percent_up          DECIMAL(10, 0),
    overvalue_hi_price  DECIMAL(10, 0),
    overvalue_lo_yield  DECIMAL(10, 2),
    sp_rating           TEXT,
    lo_52_wk            DECIMAL(10, 0),
    hi_52_wk            DECIMAL(10, 0),
    book_value          DECIMAL(10, 0),
    earnings_12_mo      DECIMAL(10, 2),
    price_to_earnings   DECIMAL(10, 0),
    pay_out             DECIMAL(10, 0),
    div_in_dgr          TEXT,
    long_term_debt      DECIMAL(10, 0),
    bluechip_criteria   DECIMAL(10, 0),
    symbol              TEXT,
    sector              TEXT,
    industry            TEXT,
    sub_sector          TEXT,
    div_growth_3_year   DECIMAL(10, 2),
    div_growth_5_year   DECIMAL(10, 2),
    div_growth_10_year  DECIMAL(10, 2),
    report_date         DATE
);

